### PR TITLE
Report error if license declaration is missing

### LINKED ISSUE #30: Handle license line
Since all files have to have a license mentioned, the rule shall be:

- the first line of an input file is
`SPDX-License-Identifier: <some license expression>`
- if no such line is present, it is considered an error
- this line is reproduced at the output as a Markdown comment like
`<!-- SPDX-License-Identifier: <the same license expression> -->`
- the line is also added as visible text at the end of the file

### PR DESCRIPTION
**Pull request by nirmal-suthar**
fixes #30

### CODE REVIEW

**Comment by nirmal-suthar** [comment]
Sample generated markdown
```md
<!-- Auto generated markdown by Spec-parser v0.0.0 -->

<!-- SPDX-License-Identifier: Community-Spec-1.0 -->

# Element

## Summary

Base domain class from which all other SPDX-3.0 domain classes derive.

## Description

An Element is a representation of a fundamental concept either directly inherent
to the Bill of Materials (BOM) domain or indirectly related to the BOM domain
and necessary for contextually characterizing BOM concepts and relationships.
Within SPDX-3.0 structure this is the base class acting as a consistent,
unifying, and interoperable foundation for all explicit
and inter-relatable content objects.

## Metadata

- name: Element
- SubclassOf: none
- Instantiability: Abstract
- Status: Stable
- id: https://spdx.org/rdf/Core#Element

## Properties

- id
  - type: idString
  - minCount: 1
  - maxCount: 1

- name
  - type: xsd:string
  - maxCount: 1
  - minCount: 0

- summary
  - type: xsd:string
  - maxCount: 1
  - minCount: 0

- description
  - type: xsd:string
  - maxCount: 1
  - minCount: 0

- comment
  - type: xsd:string
  - maxCount: 1
  - minCount: 0

- specVersion
  - type: xsd:string
  - minCount: 0
  - maxCount: *

- createdTime
  - type: xsd:dateTime
  - minCount: 0
  - maxCount: *

- createdBy
  - type: Identity
  - minCount: 0
  - maxCount: *

- profile
  - type: ProfileIdentifier
  - minCount: 1
  - maxCount: *

- dataLicense
  - type: xsd:string
  - minCount: 0
  - maxCount: *

- externalReference
  - type: ExternalReference
  - minCount: 0
  - maxCount: *

- extension
  - type: Extension
  - minCount: 0
  - maxCount: *

- verifiedUsing
  - type: IntegrityMethod
  - minCount: 0
  - maxCount: *

```

**Comment by nirmal-suthar** [comment]
> the line is also added as visible text at the end of the file
@zvr Can you please clarify what exactly the line should be?

**Comment by zvr** [comment]
Simply have the same line
> SPDX-License-Identifier: Community-Spec-1.0

as a visible separate paragraph at the end of the file.

**Comment by nirmal-suthar** [comment]
Updated generated markdown file
```md
<!-- Auto generated markdown by Spec-parser v0.0.0 -->

<!-- SPDX-License-Identifier: Community-Spec-1.0 -->

# Element

## Summary

Base domain class from which all other SPDX-3.0 domain classes derive.

## Description

An Element is a representation of a fundamental concept either directly inherent
to the Bill of Materials (BOM) domain or indirectly related to the BOM domain
and necessary for contextually characterizing BOM concepts and relationships.
Within SPDX-3.0 structure this is the base class acting as a consistent,
unifying, and interoperable foundation for all explicit
and inter-relatable content objects.

## Metadata

- name: Element
- SubclassOf: none
- Instantiability: Abstract
- Status: Stable
- id: https://spdx.org/rdf/Core#Element

## Properties

- id
  - type: idString
  - minCount: 1
  - maxCount: 1

- name
  - type: xsd:string
  - maxCount: 1
  - minCount: 0

- summary
  - type: xsd:string
  - maxCount: 1
  - minCount: 0

- description
  - type: xsd:string
  - maxCount: 1
  - minCount: 0

- comment
  - type: xsd:string
  - maxCount: 1
  - minCount: 0

- specVersion
  - type: xsd:string
  - minCount: 0
  - maxCount: *

- createdTime
  - type: xsd:dateTime
  - minCount: 0
  - maxCount: *

- createdBy
  - type: Identity
  - minCount: 0
  - maxCount: *

- profile
  - type: ProfileIdentifier
  - minCount: 1
  - maxCount: *

- dataLicense
  - type: xsd:string
  - minCount: 0
  - maxCount: *

- externalReference
  - type: ExternalReference
  - minCount: 0
  - maxCount: *

- extension
  - type: Extension
  - minCount: 0
  - maxCount: *

- verifiedUsing
  - type: IntegrityMethod
  - minCount: 0
  - maxCount: *


SPDX-License-Identifier: Community-Spec-1.0
```

**Pull request merged**
