### PR TITLE
add Format parsing for properties and add pattern restriction to SHACL

### PR DESCRIPTION
**Pull request by armintaenzertng**
This will fix the parsing problem introduced by https://github.com/spdx/spdx-3-model/pull/377.

### CODE REVIEW

**Review by maxhbr — APPROVED** [review]
LGTM


Offtopic: The parser code is really not nice and not maintainable / potential refactoring will be crazy hard. I think we need to invest some work to not build something that in the end is not sustainable for the Project.

**Comment by armintaenzertng** [comment]
As https://github.com/spdx/spdx-3-model/pull/377 has been closed, this can be closed, too.

**Comment by zvr** [comment]
I am not sure that this should have been closed and deleted. Did we ever say that we do not allow this pattern any more and everything has to be a new Datatype?

**Comment by armintaenzertng** [comment]
Now that we have the Datatype directory, I think it would be consistent to use it throughout the spec for upcoming similar issues.
If we decide against that, we can reopen this PR (or write a new one with some cleaner code ;) ).

**Pull request closed without merging**
