### PR TITLE
Add properties to SpecClasses in RDF

### LINKED ISSUE #35: Add properties to Classes in RDF
While trying to convert the markdown specification into RDF I noticed that the classes in the resulting rdf turtle file do not contain their properties. After studying the SPDX 2 ontology, I believe it should look something like this, for example:
```
core:ExternalReference a owl:Class ;
    rdfs:comment """An External Reference is a grouping of characteristics unique to the identity,
location and context of a resource outside of the scope of SPDX-3.0 content.""" ;
    rdfs:subClassOf [ a owl:Restriction ;
            owl:maxQualifiedCardinality "1"^^xsd:nonNegativeInteger ;
            owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger ;   <--- this is not needed, is it?
            owl:onClass xsd:string ;
            owl:onProperty core:comment ],
        [ a owl:Restriction ;
            owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger ;
            owl:onClass xsd:anyURI ;
            owl:onProperty core:locator ],
        [ a owl:Restriction ;
            owl:maxQualifiedCardinality "1"^^xsd:nonNegativeInteger ;
            owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger ;
            owl:onClass someSpec:MediaType ;                       <--- what defines the type MediaType?
            owl:onProperty core:contentType ],
        [ a owl:Restriction ;
            owl:maxQualifiedCardinality "1"^^xsd:nonNegativeInteger ;
            owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger ;
            owl:onClass core:ExternalReferenceType ;
            owl:onProperty core:externalReferenceType ],
    ns0:term_status "Stable" .
```

@zvr: Is this correct? If yes, I would try my hand at implementing this.

### PR DESCRIPTION
**Pull request by armintaenzertng**
will fix #35

### CODE REVIEW

**Comment by armintaenzertng** [comment]
@zvr: Example excerpt from the `tst.ttl` now looks like this:
```
core:ExternalReference a owl:Class ;
    rdfs:comment """An External Reference is a grouping of characteristics unique to the identity,
location and context of a resource outside of the scope of SPDX-3.0 content.""" ;
    rdfs:subClassOf [ a owl:Restriction ;
            owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger ;
            owl:onClass xsd:anyURI ;
            owl:onProperty core:locator ],
        [ a owl:Restriction ;
            owl:maxQualifiedCardinality "1"^^xsd:nonNegativeInteger ;
            owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger ;
            owl:onClass core:ExternalReferenceType ;
            owl:onProperty core:externalReferenceType ],
        [ a owl:Restriction ;
            owl:maxQualifiedCardinality "1"^^xsd:nonNegativeInteger ;
            owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger ;
            owl:onClass core:MediaType ;
            owl:onProperty core:contentType ],
        [ a owl:Restriction ;
            owl:maxQualifiedCardinality "1"^^xsd:nonNegativeInteger ;
            owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger ;
            owl:onClass xsd:string ;
            owl:onProperty core:comment ],
        core:none ;
    ns0:term_status "Stable" .
```
Apart from the MediaType URI (which currently defaults to the underlying profile `Core`; which would be the right reference?), is there anything amiss?

**Comment by zvr** [comment]
Discussed on 2023-03-28 tech call.

Cardinality restrictions should be in SHACL, not in pure OWL ontology.

A generic example (off the top my head) would be:

```
core:myclass
	a	owl:Class ,
I		sh:NodeShape ;
	sh:targetClass core:myclass ;
	sh:property [
		sh:path		core:myproperty ;
		sh:maxCount	"1"^^xsd:integer ;
		sh:datatype	xsd:string ;
		sh:pattern	"^\\d{3}-\\d{2}-\\d{4}$" ;
	] ;
	sh:closed	true .
```

**Review by zvr — APPROVED** [review]

**Comment by armintaenzertng** [comment]
I rebased the branch on the current `main`. Parsing of the spec proceeds without errors in the fixed version (https://github.com/spdx/spdx-3-model/pull/235).

@zvr: Should be good to merge now! :)

**Review by maxhbr — APPROVED** [review]
LGTM

**Pull request merged**
