### PR TITLE
Make inheritance tree + bold metadata headings

### PR DESCRIPTION
**Pull request by bact**
- Add bold style for readability of metadata information
- Add tree formatting for readability of superclass information

Before:

- The table orientation is not obvious (does "CustomLicense" a table header?)
- The order of inheritance is not very obvious

After:

- Bold text on the left column of metadata table, make it clearer that it is the "header"
- Tree-like inheritance list with indents, make it clearer about the direction of inheritance

(See [live](https://bact.github.io/spdx-spec/v3.0.1/model/ExpandedLicensing/Classes/CustomLicense/))

--

Reference - the style is taken from programming language doc, like [Java doc](https://docs.oracle.com/javase/8/docs/api/):

### CODE REVIEW

**Comment by zvr** [comment]
I disagree with bold (even Java docs don't use it) and I don't want to create something that will be so different in the PDF. 

Also in RDF, they say the support inheritance, but don't actually call it like that -- that's why I used the term they use (Superclass).

**Comment by bact** [comment]
Edited the PR summary, to make it less ambiguous, to:
- Add bold style for readability of metadata information
- Add tree formatting for readability of superclass information

--

Superclass tree formatting:
- Renamed Inheritance to Superclasses, and remove the bold in the last line of superclass list.
- Still retain the tree formatting.

Metadata bold style:
- This is the one that I insist
- Without the heading, the metadata table awkward and it's require some cognitive pause to figure out which reading direction is intended:
  
  OR
  
- With the bold style of the metadata table heading, it gives some clue:

**Comment by zvr** [comment]
Please don't merge anything in main!!!
I've already explained that I have many changes to completely re-work the output, so anything will create conflicts and I don't have the time to work on resolving them.

**Comment by zvr** [comment]
I like this, but I have to work on implementing it in LaTeX for PDF output, now...

**Comment by bact** [comment]
> Please don't merge anything in main!!!
> I've already explained that I have many changes to completely re-work the output that are not merged waiting for spec automation, so anything will create conflicts and I don't have the time to work on resolving them.

? 
I only tried it in my own repo and not in the SPDX repo.

**Comment by zvr** [comment]
Sorry, @bact -- my comment was meant as a warning/request not to merge anything, not that you did it already.

**Pull request merged**
