### PR TITLE
Fix named individuals in JSON-LD context

### PR DESCRIPTION
**Pull request by JPEWdev**
The "global" named individuals (e.g. NoneElement) were not added to the JSON-LD context, likely because the heuristic used to identify them was broken. Fix this, but use a different mechanism that finds all vocab values values, and anything that is not a vocab is considered to be a "global" named individual.

### CODE REVIEW

**Comment by JPEWdev** [comment]
@zvr @goneall This should fix the named individuals in the context

**Review by goneall — APPROVED** [review]
LGTM - Thanks @JPEWdev

**Comment by goneall** [comment]
@zvr if this looks good to you, pls. merge in - I'd like to include in the 3.0.1 context file.

**Comment by zvr** [comment]
LGTM.
I'll merge right after merging the changes for the new output, to avoid/minimize merge conflicts.

**Comment by JPEWdev** [comment]
Fixes #145

**Pull request merged**
