### PR TITLE
Add creationInfo to named individuals

### LINKED ISSUE #153: RDF.type of non-vocabulary named individuals may cause cadinality validation error
## Background

- In post-3.0.0 spec-parser, RDF.type was added to non-vocabulary named individuals, so SHACL can validate that the node is of the correct type (see rational here https://github.com/spdx/spec-parser/pull/135)
- `NoneElement` and `NoAssertionElement` are of type `Element`
- `NoneLicense` and `NoAssertionLicense` are of type `IndividualLicensingInfo` (also subclass of `Element`)

## The issue

- `Element` also requires at least one `creationInfo`
- But none of None* and NoAssertion* have that property set, so the validation failed (see https://github.com/spdx/spdx-spec/actions/runs/10806923739/job/30003235732?pr=1107)

### PR DESCRIPTION
**Pull request by bact**
Add `creationInfo` to named individuals, so it will pass the validation.

To fix #153

Based on https://github.com/spdx/spec-parser/issues/153#issuecomment-2344300010 and rely on `SpdxOrganization` individual to be created from https://github.com/spdx/spdx-3-model/pull/880

--

Generated spdx-model.ttl:

```
@prefix ns1: <https://spdx.org/rdf/3.0.1/terms/Core/> .
@prefix ns7: <https://spdx.org/rdf/3.0.1/terms/ExpandedLicensing/> 

ns1:_SpdxOrganization a owl:NamedIndividual,
        ns1:Organization ;
    rdfs:comment "SPDX Project"@en ;
    ns1:creationInfo _:_CreationInfo ;
    ns1:spdxId <https://spdx.org/> .

ns1:NoAssertionElement a owl:NamedIndividual,
        ns1:Element ;
    rdfs:comment """An Individual Value for Element representing a set of Elements of unknown
identify or cardinality (number)."""@en ;
    ns1:creationInfo _:_CreationInfo .

ns1:NoneElement a owl:NamedIndividual,
        ns1:Element ;
    rdfs:comment """An Individual Value for Element representing a set of Elements with
cardinality (number/count) of zero."""@en ;
    ns1:creationInfo _:_CreationInfo .

ns7:NoAssertionLicense a owl:NamedIndividual,
        ns7:IndividualLicensingInfo ;
    rdfs:comment """An Individual Value for License when no assertion can be made about its actual
value."""@en ;
    owl:sameAs <https://spdx.org/rdf/3.0.1/terms/Licensing/NoAssertion> ;
    ns1:creationInfo _:_CreationInfo .

ns7:NoneLicense a owl:NamedIndividual,
        ns7:IndividualLicensingInfo ;
    rdfs:comment """An Individual Value for License where the SPDX data creator determines that no
license is present."""@en ;
    owl:sameAs <https://spdx.org/rdf/3.0.1/terms/Licensing/None> ;
    ns1:creationInfo _:_CreationInfo .

_:_CreationInfo a ns1:CreationInfo ;
    ns1:created "2024-09-13T00:00:00Z"^^xsd:dateTimeStamp ;
    ns1:createdBy ns1:_SpdxOrganization ;
    ns1:specVersion "3.0.1"^^xsd:string .
```

### CODE REVIEW

**Comment by zvr** [comment]
No, this is not the right way to add the SPDX Individual Organization.

It should be added to the model / Core / Individuals.

**Comment by bact** [comment]
Does it mean it is possible for the user to use the _SpdxOrganization individual?

**Comment by bact** [comment]
The intention of the current code is to hide the `_SpdxOrganization` from the public spec documentation. This is also partly reflected in the naming by using a prefix `_`.

But if we like to advertise the `_SpdxOrganization` (probably with a new name "SpdxOrganization") in the public spec, can remove that part of the code and create another PR in spdx-3-model instead.

**Comment by zvr** [comment]
@bact, please don't spend time implementing stuff without first having reached consensus on how this should be done. I feel bad seeing all this work implementing alternatives where only one of them will be merged...

To your points:

- we will have an individual referring to the SPDX organization in our model
- the RDF generation of all individuals will be using this (hard-wired as creator)

But please, ignore the spec-parser code and don't make any PRs.
Due to tomorrow's deadline I will _not_ be merging anything (since it might not match what I am currently using). I _will_ be doing any necessary changes to whatever I have and I will push these sometime next week.

**Comment by bact** [comment]
Thank you for review. I sometimes have hard time to describe what I have in my mind, so some code can help myself saying it more concretely and hopefully help others well, for them to decide if the idea is a no or a go or something needs to be revise. Please reject things that doesn't make sense or not fit into the time frame.

- I have removed the _SpdxOrganization from this PR (to use one in the model)
- Retain the hard-wired  CreationInfo here

Understand your point on deadline. Feel free to close this PR if you already implemented it.

**Comment by goneall** [comment]
Just FYI - @JPEWdev is investigating an alternative approach where we separate the ontology from the SHACL.  It looks like if we do this, the validation will pass since the individual definitions will be in the OWL document.

This alternative approach would require some changes to some of our code generation tools, but may be a cleaner approach.

**Comment by sbarnum** [comment]
The identifier for the creationInfo needs to be more than simply "_:_CreationInfo".
It needs to be specific to the particular release (something like "_:_v3.0.1CreationInfo",
In future versions of SPDX there may be multiple different predefined named individuals that were defined in different releases. Their creationInfo details need to be kept distinct and integrous.
A future version 3.1.0 would keep the "_:_v3.0.1CreationInfo" (and its use within predefined named individuals defined in 3.0.1) and add a new "_:_v3.1.0CreationInfo" to be used by any new predefined named individuals if there are any added in 3.1.0.

**Comment by JPEWdev** [comment]
@sbarnum Splitting the files is (AFAICT) the expected way that the validation tools handle this. They all(?) allow separate aregument for the shapes graph vs the ontology, where objects in the shapes graph are are validated, but objects in the ontology are not validated.

Splitting the shapes and ontology graphs into separate files is going to be the cleanest solution that aligns with the validation tools, and we can still easily generate a combined "model" graph if that is what OMG needs (I'm not sure if they care about the shape graph or not)

**Comment by JPEWdev** [comment]
Nevermind. After playing around a little, I think I misunderstood what the validation tools were doing, so we probably need to add the creationinfo

**Comment by bact** [comment]
> The identifier for the creationInfo needs to be more than simply "_:_CreationInfo". It needs to be specific to the particular release (something like "_:_v3.0.1CreationInfo", In future versions of SPDX there may be multiple different predefined named individuals that were defined in different releases. Their creationInfo details need to be kept distinct and integrous. A future version 3.1.0 would keep the "_:_v3.0.1CreationInfo" (and its use within predefined named individuals defined in 3.0.1) and add a new "_:_v3.1.0CreationInfo" to be used by any new predefined named individuals if there are any added in 3.1.0.

@sbarnum would you recommend 
- `_:_V3_0_1_CreationInfo` or
- `_:_CreationInfoV3_0_1` ?

(We cannot use `.` inside the name)

**Comment by bact** [comment]
> The identifier for the creationInfo needs to be more than simply "_:_CreationInfo".
> It needs to be specific to the particular release (something like "_:_v3.0.1CreationInfo",
> In future versions of SPDX there may be multiple different predefined named individuals that were defined in different releases. Their creationInfo details need to be kept distinct and integrous.
> A future version 3.1.0 would keep the "_:_v3.0.1CreationInfo" (and its use within predefined named individuals defined in 3.0.1) and add a new "_:_v3.1.0CreationInfo" to be used by any new predefined named individuals if there are any added in 3.1.0.

With this requirement. We may need to have information inside the model file about which version of SPDX that a particular individual is introduced in? @sbarnum @goneall

**Comment by zvr** [comment]
I've implemented a simpler patch for this, in #159

**Comment by bact** [comment]
Close after email discussions and a separate tech call on 2024-12-05. Please look at PR #159 instead.

**Pull request closed without merging**
